from collections import Counter
from spacy import tokens

prep_docs = [(882, tokens.doc.Doc)]
label_docs = [
    (
        "label_list",
        [
            ("PERSON", "Fact Sheet"),
            ("DATE", "October, 1999"),
            ("PERSON", "Lavandula"),
            ("PERSON", "Edward F. Gilman2"),
            ("QUANTITY", "2 to 3 feet"),
            ("DATE", "the\nsummer"),
            ("ORG", "USDA"),
            ("CARDINAL", "5B"),
            ("CARDINAL", "8"),
            ("CARDINAL", "1"),
            ("CARDINAL", "7"),
            ("DATE", "year"),
            ("CARDINAL", "8"),
            ("DATE", "year"),
            ("LOC", "North America"),
            ("QUANTITY", "1 to 3 feet"),
            ("QUANTITY", "2 to 3 feet"),
            ("PRODUCT", "Leaf"),
            ("PRODUCT", "Leaf"),
            ("PRODUCT", "Leaf"),
            ("PRODUCT", "Leaf"),
            ("QUANTITY", "less than 2 inches"),
            ("DATE", "summer"),
            ("ORG", "Fruit"),
            ("ORG", "Fruit"),
            ("ORG", "Fruit"),
            ("ORG", "Fruit"),
            ("ORG", "Fruit"),
            ("ORG", "Fruit"),
            ("NORP", "Trunk"),
            ("PERSON", "Trunk"),
            ("CARDINAL", "1"),
            ("PERSON", "Fact Sheet"),
            ("ORG", "the Environmental Horticulture Department"),
            ("ORG", "Florida Cooperative Extension Service"),
            ("ORG", "Institute of Food\nand Agricultural Sciences"),
            ("ORG", "University of Florida"),
            ("DATE", "October, 1999"),
            ("CARDINAL", "2"),
            ("PERSON", "Edward F. Gilman"),
            ("ORG", "Environmental Horticulture Department"),
            ("ORG", "Cooperative Extension Service"),
            ("ORG", "Institute of Food and Agricultural Sciences"),
            ("ORG", "University\n"),
            ("GPE", "Florida"),
            ("GPE", "Gainesville"),
            ("DATE", "32611"),
            ("ORG", "The Institute of Food and Agricultural Sciences"),
            ("ORG", "Cooperative Extension Service"),
            ("ORG", "Florida Cooperative\n"),
            ("PERSON", "Dean\n\n\x0c"),
            ("CARDINAL", "1"),
            ("DATE", "Current year"),
            ("PERSON", "loam"),
            ("QUANTITY", "24 to 36 inches"),
            ("DATE", "winter"),
            ("ORG", "Use and Management"),
            ("QUANTITY", "several inches"),
            ("DATE", "winter"),
            ("DATE", "winter"),
            ("CARDINAL", "6"),
            ("GPE", "potpourris"),
            ("PERSON", "Bowles"),
            ("WORK_OF_ART", "Folgate"),
            ("PERSON", "Gwendolyn Anley"),
            ("WORK_OF_ART", "Hidcote’"),
            ("PERSON", "Mitcham Grey’"),
            ("WORK_OF_ART", "Rosea"),
            ("ORG", "Summerland Supreme’"),
            ("WORK_OF_ART", "Twickel Purple"),
            ("DATE", "October 1999"),
            ("CARDINAL", "Four"),
            ("NORP", "Pests"),
            ("DATE", "October 1999"),
        ],
    ),
    (
        "ents",
        [
            "Fact Sheet",
            "October, 1999",
            "Lavandula",
            "Edward F. Gilman2",
            "2 to 3 feet",
            "the summer",
            "USDA",
            "5B",
            "8",
            "1",
            "7",
            "year",
            "8",
            "year",
            "North America",
            "1 to 3 feet",
            "2 to 3 feet",
            "Leaf",
            "Leaf",
            "Leaf",
            "Leaf",
            "less than 2 inches",
            "summer",
            "Fruit",
            "Fruit",
            "Fruit",
            "Fruit",
            "Fruit",
            "Fruit",
            "Trunk",
            "Trunk",
            "1",
            "Fact Sheet",
            "the Environmental Horticulture Department",
            "Florida Cooperative Extension Service",
            "Institute of Food and Agricultural Sciences",
            "University of Florida",
            "October, 1999",
            "2",
            "Edward F. Gilman",
            "Environmental Horticulture Department",
            "Cooperative Extension Service",
            "Institute of Food and Agricultural Sciences",
            "University ",
            "Florida",
            "Gainesville",
            "32611",
            "The Institute of Food and Agricultural Sciences",
            "Cooperative Extension Service",
            "Florida Cooperative ",
            "Dean \x0c",
            "1",
            "Current year",
            "loam",
            "24 to 36 inches",
            "winter",
            "Use and Management",
            "several inches",
            "winter",
            "winter",
            "6",
            "potpourris",
            "Bowles",
            "Folgate",
            "Gwendolyn Anley",
            "Hidcote’",
            "Mitcham Grey’",
            "Rosea",
            "Summerland Supreme’",
            "Twickel Purple",
            "October 1999",
            "Four",
            "Pests",
            "October 1999",
        ],
    ),
    (
        "count",
        Counter(
            {
                "Fruit": 6,
                "Leaf": 4,
                "1": 3,
                "winter": 3,
                "Fact Sheet": 2,
                "October, 1999": 2,
                "2 to 3 feet": 2,
                "8": 2,
                "year": 2,
                "Trunk": 2,
                "Institute of Food and Agricultural Sciences": 2,
                "Cooperative Extension Service": 2,
                "October 1999": 2,
                "Lavandula": 1,
                "Edward F. Gilman2": 1,
                "the summer": 1,
                "USDA": 1,
                "5B": 1,
                "7": 1,
                "North America": 1,
                "1 to 3 feet": 1,
                "less than 2 inches": 1,
                "summer": 1,
                "the Environmental Horticulture Department": 1,
                "Florida Cooperative Extension Service": 1,
                "University of Florida": 1,
                "2": 1,
                "Edward F. Gilman": 1,
                "Environmental Horticulture Department": 1,
                "University": 1,
                "Florida": 1,
                "Gainesville": 1,
                "32611": 1,
                "The Institute of Food and Agricultural Sciences": 1,
                "Florida Cooperative": 1,
                "Dean": 1,
                "Current year": 1,
                "loam": 1,
                "24 to 36 inches": 1,
                "Use and Management": 1,
                "several inches": 1,
                "6": 1,
                "potpourris": 1,
                "Bowles": 1,
                "Folgate": 1,
                "Gwendolyn Anley": 1,
                "Hidcote’": 1,
                "Mitcham Grey’": 1,
                "Rosea": 1,
                "Summerland Supreme’": 1,
                "Twickel Purple": 1,
                "Four": 1,
                "Pests": 1,
            }
        ),
    ),
    (
        "labels",
        [
            "GPE",
            "WORK_OF_ART",
            "DATE",
            "LOC",
            "ORG",
            "PERSON",
            "PRODUCT",
            "NORP",
            "CARDINAL",
            "QUANTITY",
        ],
    ),
    (
        "index",
        {
            "PERSON": [
                "Fact Sheet",
                "Lavandula",
                "Edward F. Gilman2",
                "Trunk",
                "Fact Sheet",
                "Edward F. Gilman",
                "Dean \x0c",
                "loam",
                "Bowles",
                "Gwendolyn Anley",
                "Mitcham Grey’",
            ],
            "DATE": [
                "October, 1999",
                "the summer",
                "year",
                "year",
                "summer",
                "October, 1999",
                "32611",
                "Current year",
                "winter",
                "winter",
                "winter",
                "October 1999",
                "October 1999",
            ],
            "QUANTITY": [
                "2 to 3 feet",
                "1 to 3 feet",
                "2 to 3 feet",
                "less than 2 inches",
                "24 to 36 inches",
                "several inches",
            ],
            "ORG": [
                "USDA",
                "Fruit",
                "Fruit",
                "Fruit",
                "Fruit",
                "Fruit",
                "Fruit",
                "the Environmental Horticulture Department",
                "Florida Cooperative Extension Service",
                "Institute of Food and Agricultural Sciences",
                "University of Florida",
                "Environmental Horticulture Department",
                "Cooperative Extension Service",
                "Institute of Food and Agricultural Sciences",
                "University ",
                "The Institute of Food and Agricultural Sciences",
                "Cooperative Extension Service",
                "Florida Cooperative ",
                "Use and Management",
                "Summerland Supreme’",
            ],
            "CARDINAL": ["5B", "8", "1", "7", "8", "1", "2", "1", "6", "Four"],
            "LOC": ["North America"],
            "PRODUCT": ["Leaf", "Leaf", "Leaf", "Leaf"],
            "NORP": ["Trunk", "Pests"],
            "GPE": ["Florida", "Gainesville", "potpourris"],
            "WORK_OF_ART": ["Folgate", "Hidcote’", "Rosea", "Twickel Purple"],
        },
    ),
    (
        "inv_idx",
        {
            "Fact Sheet": "PERSON",
            "Lavandula": "PERSON",
            "Edward F. Gilman2": "PERSON",
            "Trunk": "NORP",
            "Edward F. Gilman": "PERSON",
            "Dean \x0c": "PERSON",
            "loam": "PERSON",
            "Bowles": "PERSON",
            "Gwendolyn Anley": "PERSON",
            "Mitcham Grey’": "PERSON",
            "October, 1999": "DATE",
            "the summer": "DATE",
            "year": "DATE",
            "summer": "DATE",
            "32611": "DATE",
            "Current year": "DATE",
            "winter": "DATE",
            "October 1999": "DATE",
            "2 to 3 feet": "QUANTITY",
            "1 to 3 feet": "QUANTITY",
            "less than 2 inches": "QUANTITY",
            "24 to 36 inches": "QUANTITY",
            "several inches": "QUANTITY",
            "USDA": "ORG",
            "Fruit": "ORG",
            "the Environmental Horticulture Department": "ORG",
            "Florida Cooperative Extension Service": "ORG",
            "Institute of Food and Agricultural Sciences": "ORG",
            "University of Florida": "ORG",
            "Environmental Horticulture Department": "ORG",
            "Cooperative Extension Service": "ORG",
            "University ": "ORG",
            "The Institute of Food and Agricultural Sciences": "ORG",
            "Florida Cooperative ": "ORG",
            "Use and Management": "ORG",
            "Summerland Supreme’": "ORG",
            "5B": "CARDINAL",
            "8": "CARDINAL",
            "1": "CARDINAL",
            "7": "CARDINAL",
            "2": "CARDINAL",
            "6": "CARDINAL",
            "Four": "CARDINAL",
            "North America": "LOC",
            "Leaf": "PRODUCT",
            "Pests": "NORP",
            "Florida": "GPE",
            "Gainesville": "GPE",
            "potpourris": "GPE",
            "Folgate": "WORK_OF_ART",
            "Hidcote’": "WORK_OF_ART",
            "Rosea": "WORK_OF_ART",
            "Twickel Purple": "WORK_OF_ART",
        },
    ),
]

# # in prep_docs before yield, doc.vocab.length is 882
# expected_doc_vocab_length = 882

# # doc should be a spacy.tokens.doc.Doc
# isinstance(doc, spacy.tokens.doc.Doc) is True

# # calling with a file instead of a dir should be empty
